# Install packages related to gaming 
[managers.system]
items = [
     "gamemode",
     "gpu-screen-recorder-git",
     "gpu-screen-recorder-gtk-git",
     "gpu-screen-recorder-notification",
     "lizardbyte/sunshine",
     "mangohud",
     "protonup-qt",
     "steam",
]
