# Install packages related to gaming 
[managers.system]
items = [
     "gamemode",
     "gpu-screen-recorder",
     "gpu-screen-recorder-gtk",
     "gpu-screen-recorder-notification",
     "lizardbyte/sunshine-git",
     "mangohud",
     "protontricks",
     "protonup-qt",
     "steam",
     "steamtinkerlaunch",
]
