# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
     "code",
     "gaming",
     "hyprland",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
     "bat",
     "figlet",
     "flatpak",
     "git",
     "github-cli",
     "gum",
     "keyd",
     "kitty",
     "ripgrep",
     "starship",
     "stow",
     "syncthing",
     "teamspeak3",
     "timeshift",
     "ttf-hack-nerd",
     "xorg-xhost", # Could not open apps requiring passwd without this
     "zen-browser-bin",
     "zoxide",
     "zsh",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "com.discordapp.Discord",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
