####################################
### WINDOWS AND WORKSPACES RULES ###
####################################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = name:gaming, layout:scrolling

windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# Steam Friends list rules
windowrule = match:class steam, workspace name:gaming silent
windowrule = match:class steam, match:title Friends List, float true
windowrule = match:class steam, match:title Friends List, size 300 650

# TeamSpeak and Discord on second monitor.
windowrule = match:class discord, workspace 3 silent
windowrule = match:class vesktop, workspace 3 silent
windowrule = match:class TeamSpeak 3, workspace 3 silent

# PiP for browser
windowrule = match:float true, match:title Picture-in-Picture
