####################################
### WINDOWS AND WORKSPACES RULES ###
####################################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = name:gaming, layout:scrolling

windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# Steam Friends list rules
windowrule = match:float true, match:class steam, match:title Friends List
windowrule = workspace name:gaming silent, match:class steam, match:title Friends List
windowrule = size 300 650, match:class steam, match:title Friends List

# TeamSpeak and Discord on second monitor.
windowrule = workspace 3 silent, match:class discord
windowrule = workspace 3 silent, match:class TeamSpeak 3

# PiP for browser
windowrule = match:float true, match:title Picture-in-Picture
