# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[▓](overlay)\
$username\
[ $os ](bg:overlay fg:iris)\
[](fg:overlay) \
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$fill\
$time\
\n$character(fg:rose)"""

add_newline = true

palette = "rose-pine"

[palettes.rose-pine]
overlay = "#26233a"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"

[username]
style_user = 'bg:overlay fg:gold bold'
style_root = 'bg:overlay fg:love bold'
format = '[[$user]($style) in](bg:overlay)'
disabled = false

[os]
format = "$symbol"
disabled = false

[os.symbols]
Arch = ""
CachyOS = ""
Debian = ""
EndeavourOS = ""
Linux = ""
Macos = ""
Raspbian = ""
Ubuntu = ""
Windows = "󰍲 "

[directory]
style = "bg:overlay fg:rose"
format = "[](fg:overlay)[$path]($style)[](fg:overlay) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[$symbol $branch ]($style)"
truncation_length = 30
truncation_symbol = "…/"

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!](bg:overlay fg:gold)'
renamed = '[»](bg:overlay fg:iris)'
deleted = '[✘](style)'
staged = '[++](bg:overlay fg:gold)'
ahead = '[⇡](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡](bg:overlay fg:foam)[⇣](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣](bg:overlay fg:rose)'

[fill]
style = "fg:overlay"
symbol = " "

[nodejs]
symbol = ""
style = "bg:overlay"
format = '[](fg:overlay)[[$symbol ($version)](fg:foam bg:overlay)]($style)[](fg:overlay) '

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "bg:overlay fg:rose"
#format = '[[ 󰥔 $time ](fg:#a0a9cb bg:#1d2230)]($style)'
format = " [](fg:overlay)[ $time 󰥔 ]($style)[](fg:overlay)"
